const about1 = [
	'They love',
	'They enjoy',
	'Their passion is',
	'They\'re particularly interested in',
	'They avoid',
	'The thing they hate most is',
	'They\'re grossed out by people who are into',
	'They have a strong appreciation for',
	'They are drawn to',
	'They have a deep understanding of',
	'They are fascinated by',
	'They have a keen interest in',
	'They are always ',
	'They are motivated by',
	'They are driven by',
	'They are deeply invested in',
	'They are committed to',
	'They are dedicated to',
	'They aren\'t very fond of',
	'They have a strong distaste for',
	'They have a strong aversion to',
	'They\'re repelled by',
	'They\'re grossed out by',
	'They\'re turned off by',
];

const about2 = [
	'exploring the art of',
	'collecting',
	'listening to',
	'talking about',
	'tarot card readings about',
	'solving the problem of',
	'the history of',
	'seeking new knowledge about',
	'enjoying nature and',
	'exploring new places and',
	'reading about',
	'learning about',
	'discovering new music and',
	'fascinated by',
	'finding joy in',
	'admiring',
	'fascinated with the mysteries of',
	'understanding the complexities of',
	'reflecting on',
	'contemplating the meaning of',
	'seeking answers to',
	'the harsh reality of',
	'defrauding',
	'hiding their involvement with',
	'',
];

const about3 = [
	'stuffed animals.',
	'sinewaves.',
	'the abyss.',
	'asteroids.',
	'citrus-based fruits.',
	'blood.',
	'software development.',
	'headpats.',
	'pyrotechnics.',
	'sharks.',
	'koifish.',
	'jury duty.',
	'the IRS.',
	'the mariana trench.',
	'the final boss.',
	'the illuminati.',
	'THE ALL-SEEING-ONE.',
	'vtubers.',
	'semi-trucks.',
	'other people\'s shoes.',
	'cellphones.',
	'pairs of pants.',
	'wallet keys.',
	'social media.',
	'wet paint.',
	'cats.',
	'accounting software.',
	'the raid.',
	'crime.',
	'the group DM.',
	'sport-related brain injuries.',
	'bees.',
	'forbidden tomes.',
	'precious gems.',
	'micro-blogging.',
	'fine art.',
	'money laundering.',
	'The Art of War.',
	'Wacdonalds.',
	'eating leaves.',
	'exotic imports.',
	'the supply shortage.',
	'radioactive isotope Caesium-137.',
	'a vague sense of dread.',
	'fire spinning.',
	'fire eating.',
	'calligraphy.',
	'origami.',
	'papercraft.',
	'mongolian basket weaving.',
	'pottery.',
	'sculpting their abs.',
	'woodworking.',
	'metalworking.',
	'leatherworking.',
	'mechatronics.',
	'the singularity.',
	'touching grass.',
	'hololive.',
	'men.',
	'women.',
	'spaghetti.',
	'other DEVILS.',
	'the elderly.',
	'elves.',
	'blacksmithing.',
	'cooking.',
	'crocheting.',
	'cute stuff.',
	'exploring.',
	'fencing.',
	'fishing.',
	'beachcombing.',
	'gardening.',
	'heavy metal.',
	'making friends.',
	'motorcycles.',
	'mystery novels.',
	'abandoned buildings.',
	'amateur astronomy.',
	'architecture.',
	'attention.',
	'badminton.',
	'napping.',
	'perfume.',
	'pressed flowers.',
	'sewing.',
	'shopping.',
	'studying.',
	'the outdoors.',
	'thunderstorms.',
	'weightlifting.',
	'taxidermy.',
	'fossils.',
	'cryptozoology.',
	'geocaching.',
	'entomology.',
	'astronomy.',
	'astrology.',
	'paleontology.',
	'heliocentrism.',
	'amplitude modulation.',
	'quantum mechanics.',
	'astrophysics.',
	'meteorology.',
	'dark matter.',
	'black holes.',
	'robotics.',
	'artificial intelligence.',
	'cybersecurity.',
	'virtual reality.',
	'augmented reality.',
	'cryptography.',
	'holography.',
	'kinetics.',
	'calculus.',
	'their waifu.',
	'firewalking.',
	'perfectly round birds.',
	'animal\'s toe beans.',
	'man-made horrors beyond comprehension.',
	'the power of friendship.',
	'dante\'s inferno.',
	'bitcoin maxis.',
	'web3 enthusiasts.',
	'pepo.',
	'............... MY MOM. WOOOOOOOOOO!!!',
	'weed.',
	'tax evasion.',
	'the vOiD.',
	'videogame movie adaptations.',
	'corn.',
	'chickens.',
	'backgammon.',
	'the public at large.',
	'giant squids.',
	'artificial intelligence.',
	'time travel.',
	'space exploration.',
	'virtual reality.',
	'cryptocurrency mining.',
	'renewable energy.',
	'quantum computing.',
	'underwater cities.',
	'the information super highway.',
	'3D printing.',
	'the future of france.',
	'blacksmithing.',
	'cooking.',
	'stealing.',
	'cute things.',
	'exploring.',
	'fencing.',
	'fishing.',
	'treasure hunting.',
	'gardening.',
	'heavy metal.',
	'making friends.',
	'motorcycles.',
	'mystery novels.',
	'abandoned buildings.',
	'amateur astronomy.',
	'architecture.',
	'attention.',
	'badminton.',
	'napping.',
	'nice smelling things.',
	'pressed flowers.',
	'sewing.',
	'shopping.',
	'studying.',
	'the outdoors.',
	'thunderstorms.',
	'weightlifting.',
	'taxidermy.',
	'fossils.',
	'cryptozoology.',
	'geocaching.',
	'entomology.',
	'mycology.',
	'astronomy.',
	'astrology.',
	'paleontology.',
	'heliocentrism.',
	'amplitude modulation.',
	'quantum mechanics.',
	'astrophysics.',
	'meteorology.',
	'dark matter.',
	'black holes.',
	'robotics.',
	'artificial intelligence.',
	'cybersecurity.',
	'virtual reality.',
	'augmented reality.',
	'cryptography.',
	'holography.',
	'trading stonks.',
	'calculus.',
	'clowns.',
	'juggling.',
	'glassblowing.',
	'pyrotechnics.',
	'firewalking.',
	'fire spinning.',
	'fire eating.',
	'calligraphy.',
	'traditional art.',
	'papercraft.',
	'knitting.',
	'videogames.',
	'cats :3.',
	'escape rooms.',
	'working out.',
	'dogs :3.',
	'sculpting.',
	'woodworking.',
	'metalworking.',
	'leatherworking.',
	'mechatronics.',
	'crime.',
	'shapeshifting.',
	'buying shitcoins.',
	'holding bags.',
	'leg day.',
];

const about1a = [
	'They\'re always trying to',
	'Their dream is to',
	'They\'re in training to',
	'One day, they\'ll',
	'They\'re constantly working to',
	'They\'re determined to',
	'They\'re striving to',
	'Their ambition is to',
	'They\'re on a mission to',
	'They\'re eager to',
	'They\'re always looking for new ways to',
	'They make it a point to',
	'They can\'t resist the urge to',
	'They love to',
	'They enjoy when their friends',
	'They want to learn how to',
	'They are deeply invested in the plot to',
	'They avoid the urge to',
	'The thing they hate most is not being able to',
	'They are driven by the desire to',
];

const about2a = [
	'infiltrate',
	'steal from',
	'escape from',
	'destroy',
	'reverse-engineer',
	'outsmart',
	'become',
	'scam',
	'take down',
	'break into ',
	'defeat',
	'eliminate',
	'sabotage',
	'consume',
	'manipulate',
	'reanimate',
	'exploit',
	'dismantle',
	'transcend',
	'extrapolate',
	'transmute',
	'join a cult based around',
	'be part of a secret society about',
	'give away',
	'collect',
	'understand the complexities of',
	'rid the world of',
	'solve the great mystery of',
	'seek new knowledge about',
	'hide their involvement with',
	'look for',
	'defraud',
];

const about3a = [
	'sharks.',
	'koifish.',
	'jury duty.',
	'the IRS.',
	'the mariana trench.',
	'the final boss.',
	'the illuminati.',
	'THE ALL-SEEING-ONE.',
	'sinewaves.',
	'the abyss.',
	'asteroids.',
	'citrus-based fruits.',
	'software development.',
	'other people\'s shoes.',
	'cellphones.',
	'pants.',
	'wallet keys.',
	'social media.',
	'cats.',
	'the raid.',
	'crime.',
	'the group DM.',
	'semi-trucks.',
	'bees.',
	'forbidden tomes.',
	'precious gems.',
	'micro-blogging.',
	'fine art.',
	'money laundering.',
	'The Art of War.',
	'Wacdonalds.',
	'the establishment.',
	'exotic imports.',
	'the supply shortage.',
	'radioactive isotope Caesium-137.',
	'the vague sense of dread.',
	'papercraft.',
	'men.',
	'women.',
	'spaghetti.',
	'other DEVILS.',
	'the elderly.',
	'elves.',
	'abandoned buildings.',
	'the moon.',
	'the outdoors.',
	'the mongolian basket weaving forum.',
	'the singularity.',
	'touching grass.',
	'hololive.',
	'their wallet keys.',
	'dogs.',
	'man-made horrors beyond comprehension.',
	'the power of friendship.',
	'dante\'s inferno.',
	'bitcoin maxis.',
	'web3 enthusiasts.',
	'pepo.',
	'tax evasion.',
	'the vOiD.',
	'corn.',
	'chickens.',
	'the public at large.',
	'artificial intelligence.',
	'time travel.',
	'virtual reality.',
	'the information super highway',
	'the future of france.',
	'mystery novels.',
	'abandoned buildings.',
	'amateur astronomy.',
	'treasure hunting.',
	'nice smelling things.',
	'trading stonks.',
	'shapeshifting.',
	'cats :3',
	'escape rooms.',
	'working out.',
	'dogs :3',
	'leg day.',
];

const about1b = [
	'Their biggest fear is being',
	'Their personal goal is to be',
	'They will never be',
	'They\'re always trying to avoid being',
	'Their dream is to be',
	'They\'re in training to be',
	'One day, they\'ll fulfill the prophecy and be',
	'They\'re constantly working to be',
	'They\'re determined to be',
	'They\'re striving to be',
	'Their ambition is to be',
	'They\'re on a mission to be',
	'They\'re eager to be',
	'They\'re always looking for new ways to be',
];

const about2b = [
	'killed by',
	'caught by',
	'judged by',
	'seen by',
	'cancelled by',
	'struck by',
	'discovered by',
	'stepped on by',
	'freed from',
	'admired by',
	'part of a cult surrounding',
	'recognized for their work in',
	'under suspicion of the fed for',
];

const about3b = [
	'tubbycats :3',
	'THE ALL-SEEING-ONE.',
	'a smooth criminal.',
	'a semi-truck.',
	'a catgirl',
	'other people\'s shoes.',
	'a vtuber.',
	'asteroids.',
	'citrus-based fruits.',
	'sharks.',
	'koifish.',
	'jury duty.',
	'the IRS.',
	'the mariana trench.',
	'the final boss.',
	'the illuminati.',
	'THE ALL-SEEING-ONE.',
	'pairs of pants.',
	'wallet keys.',
	'bees.',
	'Wacdonalds.',
	'men.',
	'women.',
	'other DEVILS.',
	'the elderly.',
	'elves.',
	'their waifu.',
	'dogs.',
	'perfectly round birds.',
	'tax evasion.',
	'man-made horrors beyond comprehension.',
	'the power of friendship.',
	'dante\'s inferno.',
	'bitcoin maxis.',
	'web3 enthusiasts.',
	'pepo.',
	'............... MY MOM. WOOOOOOOOOO!!!',
	'weed.',
	'tax evasion.',
	'the vOiD.',
	'chickens.',
	'the public at large.',
	'giant squids.',
	'artificial intelligence.',
	'the future of france.',
	'the information super highway.',
	'shitcoins.',
	'dogs :3',
	'cats :3',
];

const about1c = [
	'The last time they were seen, they said they were',
	'They\'re secretly',
	'Rumor says they\'re',
	'They\'re definitely not',
	'They deny it, but they\'re',
	'They\'re constantly',
];

const about2c = [
	'hiding their involvement with',
	'under suspicion of',
	'looking for',
	'addicted to',
	'traumatized by',
	'crazy for',
	'hiding',
	'on the run from',
	'scamming',
	'plotting the downfall of',
	'admired by',
	'doing',
];

const about3c = [
	'the fed.',
	'catgirls.',
	'accounting software.',
	'the raid.',
	'crime.',
	'the group DM.',
	'THE ALL-SEEING-ONE.',
	'a smooth criminal.',
	'a semi-truck.',
	'photos of spongebob at the christmas party.',
	'tons of cocaine.',
	'your mom.',
	'asteroids.',
	'citrus-based fruits.',
	'sharks.',
	'koifish.',
	'the birds. The birds are everywhere.',
	'the IRS.',
	'the mariana trench.',
	'the final boss.',
	'the illuminati.',
	'THE ALL-SEEING-ONE.',
	'wallet keys.',
	'bees.',
	'Wacdonalds.',
	'hololive.',
	'men.',
	'women.',
	'other DEVILS.',
	'the elderly.',
	'elves.',
	'their waifu.',
	'dogs.',
	'perfectly round birds.',
	'animal\'s toe beans.',
	'man-made horrors beyond comprehension.',
	'the power of friendship.',
	'dante\'s inferno.',
	'bitcoin maxis.',
	'web3 enthusiasts.',
	'pepo.',
	'............... MY MOM. WOOOOOOOOOO!!!',
	'weed.',
	'tax evasion.',
	'the vOiD.',
	'videogame movie adaptations.',
	'corn.',
	'chickens.',
	'the public at large.',
	'giant squids.',
	'artificial intelligence.',
	'time travel.',
	'space exploration.',
	'virtual reality.',
	'cryptocurrency mining.',
	'renewable energy.',
	'quantum computing.',
	'underwater cities.',
	'the information super highway.',
	'3D printing.',
	'the future of france.',
	'clowns.',
	'mystery novel.s',
	'abandoned buildings.',
	'amateur astronomy.',
	'nice smelling things.',
	'shapeshifting.',
	'cats :3',
	'dogs :3',
	'escape rooms',
	'shitcoins',
	'leg day.',
];

export {
	about1,
	about2,
	about3,
	about1a,
	about2a,
	about3a,
	about1b,
	about2b,
	about3b,
	about1c,
	about2c,
	about3c,
};