const mainType = [
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'DEVIL',
	'ANGEL',
	'ELDRITCH',
	'HALFLING',
];

const humanity = [
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'HIGH',
	'AVERAGE',
	'AVERAGE',
	'AVERAGE',
	'AVERAGE',
	'AVERAGE',
	'AVERAGE',
	'AVERAGE',
	'AVERAGE',
	'LOW',
	'NULL',
	'∞',
	'???',
];

const races = [
	'Dragonborn',
	'Human',
	'Human',
	'Dwarf',
	'Hill Dwarf',
	'Human',
	'Mountain Dwarf',
	'Elf',
	'Human',
	'Half-Elf',
	'High Elf',
	'Human',
	'Human',
	'Wood Elf',
	'Eladrin Elf',
	'Gnome',
	'Human',
	'Human',
	'Deep Gnome',
	'Rock Gnome',
	'Human',
	'Human',
	'Halfling',
	'Lightfoot Halfling',
	'Human',
	'Human',
	'Stout Halfling',
	'Orc',
	'Human',
	'Human',
	'Half-Orc',
	'Tiefling',
];

const subType = [
	'IMP',
	'GHOST',
	'WISP',
	'MIMIC',
	'KAPPA',
	'SPRITE',
	'TENGU',
	'BAKU',
	'VAMPIRE',
	'CULTIST',
	'ZOMBIE',
	'SKELETON',
	'LIZARD',
	'ANIMATED ARMOR',
	'DRYAD',
	'NIX',
	'MIND DEVOURER',
	'FLAMESKULL',
	'SUCCUBUS',
	'INCUBUS',
	'JIANGSHI(僵尸)',
	'CRYPTID',
	'ONEIROS',
	'BASILIK',
	'BLACK DOG',
	'BUNYIP',
	'FISHMAN',
	'GRIFFIN',
	'HARPY',
	'HELL HOUND',
	'JACKALOPE',
	'JERSEY DEVIL',
	'JOROUGUMO',
	'KARASUTENGU',
	'KUCHISAKE',
	'MANTICORE',
	'OGRE',
	'ONOCENTAUR',
	'RADISH',
	'SLIME',
	'WARG',
	'NIX',
	'FUTAKUCHION\'NA (二口女)',
	'TANUKI(狸)',
	'KOROPOKKUR',
	'KODAMA',
	'POLTERGEIST',
	'CRYPTID',
	'REAPER',
];

const jobs = [
	'ACADEMIC',
	'ASTROLOGER',
	'CARTOGRAPHER',
	'JUDGE',
	'MERCHANT',
	'SCRIBE',
	'SCHOLAR',
	'STUDENT',
	'WRITER',
	'POET',
	'MERCENARY',
	'SELL-SWORD',
	'BARD',
	'CLERIC',
	'FIGHTER',
	'MONK',
	'WIZARD',
	'ARISTOCRAT',
	'ARCHITECT',
	'CARPENTER',
	'STONEMASON',
	'GLASSBLOWER',
	'ARTIST',
	'MASON',
	'ACOLYTE',
	'PRIEST',
	'SHAMAN',
	'ALCHEMIST',
	'ARMORER',
	'BAKER',
	'BOOKKEEPER',
	'PASTRY CHEF',
	'BLACKSMITH',
	'BREWER',
	'BUTCHER',
	'COBBLER',
	'COOK',
	'CHEF',
	'DYER',
	'ENGRAVER',
	'GOLDSMITH',
	'SMELTER',
	'JEWELER',
	'LEATHERWORKER',
	'LOCKSMITH',
	'CRIMINAL',
	'ASSASSIN',
	'PAINTER',
	'POTTER',
	'SKINNER',
	'TANNER',
	'TOYMAKER',
	'WOODCARVER',
	'WOODWORKER',
	'LUMBERJACK',
	'WEAPONSMITH',
	'SHIP BUILDER',
	'WEAVER',
	'PIRATE',
	'PICKPOCKET',
	'JESTER',
	'ACROBAT',
	'DANCER',
	'THIEF',
	'MINSTREL',
	'MUSICAL PRODIGY',
	'BARTENDER',
	'PROSTITUTE',
	'STORYTELLER',
	'ACTOR',
	'PLAYWRIGHT',
	'FARMER',
	'SHEEP HERDER',
	'HORSE TRAINER',
	'VETERINARIAN',
	'HUNTER',
	'BANKER',
	'TAX COLLECTOR',
	'HEALER',
	'HERBALIST',
	'WITCH',
	'MIDWIFE',
	'BROTHEL KEEPER',
	'INNKEEPER',
	'TAVERN KEEPER',
	'BEER MERCHANT',
	'SOMMELIER',
	'BOOKSELLER',
	'CARAVANNER',
	'DAIRY SELLER',
	'FISHER',
	'FLORIST',
	'GRAIN MERCHANT',
	'GROCER',
	'HABERDASHER',
	'SPICE MERCHANT',
	'SLAVER',
	'WINE MERCHANT',
	'MILLER',
	'BOUNTY HUNTER',
	'GUARD',
	'SOLDIER',
	'CITY GUARD',
	'EXPLORER',
	'SAILOR',
	'TRAVELER',
	'DIPLOMAT',
	'POLITICIAN',
	'BARBER',
	'CARRIAGE DRIVER',
	'SERVANT',
	'GARDENER',
	'ARCHAEOLOGIST',
	'ART CURATOR',
	'HISTORIAN',
	'SCULPTOR',
	'SLAVE',
	'BUTLER',
	'CANDLEMAKER',
	'BEEKEEPER',
	'CONCUBINE',
	'GEMCUTTER',
	'MESSENGER',
	'KNIGHT',
	'LANDLORD',
	'SINGER',
	'LUMBERJACK',
	'TRUSTFUND KID',
	'TRANSPORTER',
	'OUTCAST',
	'GUILDMASTER',
	'LOOKING FOR WORK',
	'UNEMPLOYED',
	'TAKES ODD JOBS',
	'MANGAKA',
	'WAGIE',
	'INTERN',
	'HITMAN',
	'SOCIAL MEDIA INFLUENCER',
	'FED',
	'CARPET MERCHANT',
	'HEDGEFUND MANAGER',
	'WEB DEVELOPER',
	'SOFTWARE ENGINEER',
	'LAWYER',
	'SECREATARY',
	'FEUNG SHUI CONSULTANT',
	'PROFESSIONAL SLEEPER',
	'SNAKE OIL SALESMAN',
	'COSPLAYER',
	'FIREFIGHTER',
	'UNDERTAKER',
	'MAKEUP ARTIST',
];

const adjs = [ //nature
	'DULL',
	'DISSONANT',
	'SULLEN',
	'BROODING',
	'GLOOMY',
	'RESIGNED',
	'SOUR',
	'TIMID',
	'ANXIOUS',
	//
	'DESTRUCTIVE',
	'MALICIOUS',
	'VENGEFUL',
	'RAVENOUS',
	'AGGRESSIVE',
	'PRETENTIOUS',
	'ARROGANT',
	'HOT-HEADED',
	//
	'MISCHIEVOUS',
	'DEVIOUS',
	'CLEVER',
	'EXCITABLE',
	'GLAMOROUS',
	'HEROIC',
	'WILD',
	'ADEPT',
	'ECCENTRIC',
	//
	'SLEEPY',
	'STOIC',
	'CALM',
	'CARELESS',
	'CURIOUS',
	'OBSERVANT',
	'RESERVED',
	'ALOOF',
	'QUIET',
	//
	'AFFECTIONATE',
	'CLUMSY',
	'DITZY',
	'CHILDISH',
	'DREAMY',
	'FRIENDLY',
	'COOL',
	'SMUG',
];

const aesth = [
	'ART NOUVEAU',
	'ATHLETIC',
	'BLACK&WHITE',
	'CASUAL',
	'COLORFUL',
	'CUTE',
	'GIRLY',
	'GRUNGY',
	'HIPSTER',
	'MESSY',
	'MONOTONE',
	'MORI KEI',
	'PASTEL GOTH',
	'PUNK',
	'RUGGED',
	'SLEEPWEAR',
	'SPORTY',
	'PUNK',
	'TAILORED',
	'WITCHY',
	'COLLAB',
	'BLEEDING',
	'HYPNOTIZED',
	'RETRO',
	'KIDCORE',
	'HARAJUKU',
	'HORROR',
	'CUTESY',
	'DEMONIC',
	'GLITCH',
	'SHITPOST',
	'ASTRAL',
];

const alignments = [
	'Lawful Good',
	'Lawful Neutral',
	'Lawful Evil',
	'Neutral Good',
	'True Neutral',
	'Neutral Evil',
	'Chaotic Good',
	'Chaotic Neutral',
	'Chaotic Evil',
];

const moralsLG = [
	'"Society has merit, and as a participant I defend it."',
	'"My Creed is my word, and my hand its upholder."',
	'"Though I may disagree, the wisdom of our elders will prevail."',
	'"There\'s nothing like the satisfaction of a made bed and folded laundry."',
	'"Justice and honor are a heavy burden for the righteous. We carry this weight so that the weak may grow strong and the meek grow brave."',
	'"Justice is all. Honor is my armor. He who commits a crime will pay. Without law and truth, there is only chaos. I am the light, I am the sword of righteousness. My enemy shall pay in the end. Right is might. My soul is pure. My word is truth."',
	'"Absolute freedom is no better than chaos. Society needs laws and regulations to protect it."',
	'"No day goes by where I am not tempted to return to my inborn nature.  What is better? To be born good, or to overcome your evil nature through great effort?"',
	'"The law is the end product of many years of history... the fruit of human knowledge! Like a gem, polished to a gleam through trials... and errors. It is this fruit we receive, and pass on, and face in our time. And it is always changing, growing. Nurturing it is our task as human beings."',
	'"He who does not punish evil, commands it to be done."',
	'"I swear to seek justice, to let it guide me, until I find a more perfect Ideal."',
];

const moralsLN = [
	'"If I have to save the world, I will."',
	'"I am the sword that enforces the will of the people."',
	'"Justice is blind."',
	'"A vow is a vow. Nothing in this world is worth more."',
	'"Justice is incidental to law and order."',
	'"Fame...justice...I\'m not interested in either. If a woman was murdered, I\'m out to find the killer. That\'s all."',
	'"A mentality compounded of two very simple principles, admirable in themselves but which, by carrying them to extremes, almost makes one evil — respect for authority and hatred of all forms of revolt against it."',
	'"Want? Agree? That has nothing to do with it. The law is the law."',
	'"No personal justice takes precedence over the world\'s justice."',
	'"The guilty must be punished."',
	'"The code is the code. The law bends for no one."',
];

const moralsLE = [
	'"Come hell or high water, I will hunt those that defy us."',
	'"There is no joy greater than seeing the fear in the eyes of those we bring to their knees."',
	'"An eye for an eye? If they take my eye, I\'ll build a beholder out of them and their kin."',
	'"Even Devils have laws. Abiding the contract gives us power, but break it, and we\'re bound as slaves."',
	'"One Vision. One Purpose. Peace Through Power."',
	'"If your enemy defies you, serve him steel and fire. But if he bends the knee, you must help him back to his feet, else no man will ever kneel to you."',
	'"Pity them not and scorn their cries of innocence - it is better that one hundred innocently fall before the wrath of the Emperor than one kneels before the Daemon."',
	'"The people are happy and content. As I have commanded they be..."',
	'"Say what you like about warlords and dictators; they always pay their bills on time."',
	'"Citizens should not fear their government. This will be enforced."',
];

const moralsNG = [
	'"The balance must be preserved."',
	'"To act in anger is to betray your own judgment."',
	'"Protect those who can\'t defend themselves above all else, then you can do as you will."',
	'"Creation and all its imperfections are divine, perversions of it will not be suffered."',
	'"Those who violate the rules and fail to follow orders are garbage. However, those who do not care for and support their fellows... are even lower than garbage!"',
	'"Surely in the ideal state governments and their people should exist happily together. Fear in either direction will lead to violence."',
	'"Rules are not necessarily sacred; principles are."',
	'"When the system works, use it. When it doesn\'t... that\'s what we are there for."',
	'"I am free, no matter what rules surround me. If I find them tolerable, I tolerate them; if I find them too obnoxious, I break them. I am free because I know that I alone am morally responsible for everything I do."',
	'"You don\'t need a reason to help people."',
	'"It was a sweet day when I realised legal and illegal had nothing to do with right and wrong."',
	'"If you feel like a broken man, and want to run away from the problems you face, if you think you can\'t fight for yourself any longer, then the answer is simple. Don\'t fight for yourself. Fight for someone else."',
];

const moralsNN = [
	'"Fuck all this shit, man."',
	'"Fate controls all things. Who am I to interfere?"',
	'"..."',
	'"Beauty in all things. Right and wrong, good and evil. Respect your ability to indulge in what you please, and do not forget that others have that same privilege."',
	'"I don\'t want to carry anyone\'s burden."',
	'"People gotta talk themselves into law and order before they do anything about it. Maybe because down deep they don\'t care. They just don\'t care."',
	'"A live body and a dead body contain the same number of particles. Structurally, there\'s no discernible difference. Life and death are unquantifiable abstracts. Why should I be concerned?"',
	'"I don\'t know, and I have no opinion."',
];

const moralsNE = [
	'"Take what you can. The only thing you can rely on is yourself."',
	'"Allies are great.. but you can find allies anywhere..."',
	'"We all die alone. I don\'t care what prayers you say or what family you have. We. All. Die. Alone."',
	'"Hmmm, maybe I should help them...or, maybe I should just help myself!"',
	'"I\'m loyal to no flag or a country or any set of ideals."',
	'"Destroy anyone who has ever slighted you."',
	'"I\'ve got no complaints as long as I get to kill who I want and steal what I want."',
	'"Don\'t apologise. I never do."',
	'"I\'m right and I refuse to elaborate."',
	'"I am not cringe. I am FREE."',
];

const moralsCG = [
	'"I don\'t care what you say. This is wrong, and I won\'t just accept it!"',
	'"I follow my heart. It tells me what is right and what must be done."',
	'"I dunno about all that... but something tells me it\'s the right thing to do."',
	'"Justice is blind and cannot see where mercy and compassion must be exercised."',
	'"I don\'t care what I become. All those who fought against witches, who believed in hope as magical girls, I don\'t want to see them cry. I want them to be smiling to the end. If any rule or law stands against that, I will destroy it. I will rewrite it."',
	'"Nobody\'s always right. Nobody\'s always good. But wanting to be? Wanting to do what\'s best so fucking much you\'ll change the rules to do it? That\'s a win in my book."',
	'"Because while the truncheon may be used in lieu of conversation, words will always retain their power. Words offer the means to meaning, and for those who will listen, the enunciation of truth"',
	'"Good men don\'t need rules."',
	'"Power does things to people. I\'ve never met a man who had it that I favoured. So I take it from them, and hope they see what remains."',
	'"My soul is good, but free. Laws have no conscience. Blind order promotes disorder. Goodness cannot be learned just from a book of prayer. Compassion does not wear a uniform. The smallest act of kindness is never wasted. Repay kindness with kindness. Be kind to someone in trouble — it may be you who needs kindness the next day."',
	'"Don\'t walk behind me; I may not lead. Don\'t walk in front of me; I may not follow. Just walk beside me and be my friend."',
	'"There is hope in the individual, in you, not in a system, not in the blueprint of a planned society, not in any religious organization, but in you, the individual."',
];

const moralsCN = [
	'"I do as I please and as I please changes from one day to the next!"',
	'"The devil is in the details and I care not for reading the fine print."',
	'"I was what you would call \'good\' once. I have indulged in what you would call a little \'evil\' as well. What matters most is the fun I had!"',
	'"Yeah, let\'s break some rules!"',
	'"Fuck around and find out."',
	'"There is no good or evil. There is only fun and boring."',
	'"You know how I so revel in chaos."',
	'"I\'m not a pawn of the Powers That Be. I\'m neither an ally of the warlocks nor of the witches. I am who I am. I\'m not a puppet of authority like you."',
	'"My world is all just shades of grey. That\'s why you\'ll never really understand me."',
	'"A rolling stone gathers no moss. There is only today. Be like the wind and be taken wherever fate sees fit. He who fights fate courts folly. You only live once. Power to those who do not wish for power. Avoid anything in a uniform. Challenge the old orders."',
	'"I don\'t fight for good, and I don\'t fight for evil. I JUST FIGHT!"',
	'"I don\'t suffer from insanity, I love every minute of it!"',
	'"I have a secret love of chaos. There should be more of it."',
	'"Do not assume that order and stability are always good. The old, the ossified, must always give way to new life and the birth of new things. Before the new things can be born the old must perish."',
];

const moralsCE = [
	'"One man\'s loss is another\'s gain."',
	'"I stand defiant of those who claim to \'represent\' people. People is a term used for animals who cannot act for themselves."',
	'"Greed is good."',
	'"If it serves me, that\'s all I need to know."',
	'"They can\'t be bought, bullied, reasoned or negotiated with. Some men just want to watch the world burn."',
	'"I do what I do, when I choose, why I wish. I answer to no one."',
	'"Destruction isn\'t supposed to make sense! It\'s only fun when it\'s senseless!"',
	'"Kill everyone now! Condone first degree murder! Advocate cannibalism! Eat shit! Filth are my politics! Filth is my life!"',
	'"Being alive is wonderful! And the most wonderful thing about life is taking it away from other people."',
	'"I love only myself. If all other people exist out there to magnify that love, then there is no more splendid world than this one. They allow me to experience the joy of living... for as long as there are people out there to kill... then I will not cease to exist."',
	'"Because once I didn\'t care about the rules anymore, I had all the power. We all have it inside of us. We just got to let it out. And I can show you how..."',
	'"Sometimes the only way to fix a system is to burn it down and start from scratch. But I\'m not interested in the \'fixing\' bit."',
	'"Schemers trying to control their little worlds. I\'m not a schemer. I try to show the schemers how pathetic their attempts to control things really are"',
	'"That which we cannot destroy, we will defile! Those we cannot defeat will know only despair!"',
	'"Tear down creation, just to see if you can."',
];

const personalityTraits = [
	'Dumber than a bag of rocks, but the kindest soul you\'ll ever meet.',
	'Likes to keep to themselves. They\'re a bit of a loner.',
	'Has a hard time relaxing because of their workaholic tendencies.',
	'Always searching for their soulmate, a hopeless romanitc.',
	'Is a bit of a know-it-all and can be hard to have a conversation with.',
	'Can be a perfectionist and too hard on themselves at times.',
	'Is fiercely independent and doesn\'t like to rely on others.',
	'Has a tendency to overthink and overanalyze situations.',
	'Is a bit of a neat freak and can\'t stand a messy environment.',
	'Is often described as spontaneous and impulsive.',
	'Can be quite stubborn and unwilling to change their mind.',
	'Is a bit of a control freak and likes to be in charge.',
	'Has a tendency to hold grudges and can be quite vengeful.',
	'Is known for their quick wit and sharp tongue.',
	'Can be quite pessimistic and tends to see the negative side of things.',
	'Values friendship and kinship over all.',
	'Is typically the life of the party.',
	'Wants to be friends with everyone.',
	'Is not very careful with words. Makes sure to blurt out every thought and every detail that comes to mind.',
	'Has a strong work ethic. Hard work builds character.',
	'Means well, but can be disloyal at times. Has tarnished a few friendships this way.',
	'Stutters and breaks eye contact when nervous.. which is all of the time.',
	'Is hardened to emotion, and rarely shows any form of expression.',
	'Is generally quiet and calculated, speaking only when it is important.',
	'Can be blunt. Says things as they are without considering others\' feelings.',
	'Brings flowers to the at the cemetary each week to pay respects to lost loved ones and strangers alike.',
	'Is a pathological liar. I wouldn\'t count on this one.',
	'Is always polite, even if it\'s disingenuous. But you would never be able to tell.',
	'Is constantly gossiping about something. Knows everything going on in town.',
	'Is a fearless and undefeated fighter. Has never been beaten in battle.',
	'Trusts strangers way too easily. A bit easy to manipulate.',
	'Is always willing to lend a hand to those in need.',
	'Spends a little too much time at the brothel.',
	'Has impossible standards and is difficult to please.',
	'Maintains a postitive outlook on life, and is sure to always lift everyone\'s spirits.',
	'Can\'t read or write, but is very sociable and happy to talk to you.',
	'Can be extremely emotional. Can be set off by small occurrences.',
	'Is a total animal lover. Would completely replace every human friend with an animal if possible. Wants to save every stray cat, dog, and horse.',
	'Is a bit of a troublemaker, and has been arrested once or twice.',
	'Will only help if you offer some coin. Will basically do anything for some coin.',
	'Enjoys stirring drama amongst the townspeople for no good reason.',
	'Is generally nice, but can be confrontational. Be careful with this one.',
	'Absolutely LOVES, lives, and breathes drama. There is never enough drama for this one.',
	'Is full of energy and can\'t stop figdgeting around. Continuously paces around the room. ',
	'Is having an affair and doesn\'t feel guilty about it.',
	'Feels betrayed by most of society due to childhood trauma.',
	'Enjoys lockpicking as a hobby.',
	'Is loved by family and friends alike. A genuinely good person.',
	'Has many enemies.',
	'Is very popular. Has a strong reputation among the people.',
	'Has a terrible reputation and wants to make amends.',
	'Is always looking for affirmation.',
	'Is a conspiracy theorist.',
	'Has a soft heart. You feel comforted in their presence.',
	'May have kleptomaniac tendencies.',
	'Is always trying to tell jokes that rarely land.',
	'Feels society has been corrupted by coin. Tries to barter whenever possible.',
	'Has a soft-spot for the downtrodden. Will always donate a spare coin.',
	'Flirts with literally everyone. Don\'t think you\'re special.',
	'Is quite the adrenaline junkie. Always up for some adventure.',
	'Is a bit absent-minded. Often gets lost in daydreams and forgets about the task at hand.',
];

export {
	mainType,
	humanity,
	races,
	subType,
	adjs,
	jobs,
	aesth,
	alignments,
	moralsLG,
	moralsLN,
	moralsLE,
	moralsNG,
	moralsNN,
	moralsNE,
	moralsCG,
	moralsCN,
	moralsCE,
	personalityTraits,
};
